### ISSUE TITLE
Peer Review - Live Demo

### ISSUE THREAD

**Issue by veerleprins** [BVictorB/blijf-ik-droog#12]
## Live Demo
- Since the diagrams are still missing, I had no idea what the flow would be. But even if I click on your live demo and enter Amsterdam with travel time '2' as location, nothing changes on the page yet. 
- I have a bit of an idea of what you are going to make (nice concept!) And that will probably be fine 😄 

## To solve this issue:

- [x] Just keep coding with everything 😄

**Comment by victorboucher** [comment]
Yeah the GH pages version had errors because it was not using my Parcel build folder yet. I solved this now! 😃
