### ISSUE TITLE
Peer Review - Browse Code

### ISSUE THREAD

**Issue by veerleprins** [BVictorB/blijf-ik-droog#13]
## Code
- Unfortunately I cannot compare it with the diagrams yet, so I have no idea if your structure and ideas are already consistent with your diagrams 😄 
- Maybe it's smart to put all that example code of the course itself in your gitignore. 😄 
- Code looks very structured! 👍 
- No idea if this breaks your code: But try to declare all your variables first in your function. You probably already know this, but in your calcDryMinutes function you don't. 
- I do see that you are using a .innerHTML (in your renderMinuteData() function) and this is a bad practice within the course [it says here](https://github.com/cmda-minor-web/best-practices/blob/master/javascript.md). Maybe you can write that different. 
But overall it all looks very neat! I think this will all work out 👍 😄 

## To solve this issue:

- [x] Add these **unnecessary files** to your .gitignore
- [x] Declare those 2 variables from your calcDryMinutes function **at the top** (unless it breaks your code)
- [x] Change **.innerHTML** to something else (in your renderMinuteData() function)

**Comment by joostf** [comment]
@veerleprins 
const bindings don't get hoisted to the top of the scope, but in most cases it makes for better code readability to declare them at the top.
