### ISSUE TITLE
Use a logical operator here for more concise code?

### ISSUE THREAD

**Issue by joostf** [BVictorB/blijf-ik-droog#16]
https://github.com/BVictorB/web-app-from-scratch-2021/blob/05714acd1535cf7224a2d6b238c9288e9d8dfa3f/scripts/modules/calcDryMinutes.js#L3

Instead of ternary operator
```minute.precipitation === 0 ? array.push(index) : null```

you could use a logical operator
```minute.precipitation && array.push(index)```

you don't seem to need an else statement here.

**Comment by victorboucher** [comment]
Awesome! Didn't think of that 😃
